<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Order\Command;

final class CancelOrder extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    const MESSAGE_NAME = 'BolCom\RetailerApi\Model\Order\Command\CancelOrder';

    protected $messageName = self::MESSAGE_NAME;

    /**
     * @return \BolCom\RetailerApi\Model\Order\Command\CancelOrderItem[]
     */
    public function orderItems(): array
    {
        $__returnValue = [];

        foreach ($this->payload['orderItems'] as $__value) {
            $__returnValue[] = CancelOrderItem::fromArray($__value);
        }

        return $__returnValue;
    }

        /**
     * @param \BolCom\RetailerApi\Model\Order\Command\CancelOrderItem[]|null $orderItems
     */
public static function with(CancelOrderItem ...$orderItems): CancelOrder
    {
        $__array_orderItems = [];

        foreach ($orderItems as $__value) {
            $__array_orderItems[] = $__value->toArray();
        }

        return new self([
            'orderItems' => $__array_orderItems,
        ]);
    }

    protected function setPayload(array $payload)
    {
        if (! isset($payload['orderItems']) || ! \is_array($payload['orderItems'])) {
            throw new \InvalidArgumentException("Key 'orderItems' is missing in payload or is not an array");
        }

        foreach ($payload['orderItems'] as $__value) {
            if (! \is_array($__value)) {
                throw new \InvalidArgumentException("Key 'orderItems' is not an array of arrays in payload");
            }
        }

        $this->payload = $payload;
    }
}
