<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Order\Command;

final class CancelOrder
{
    private $orderItemId;
    private $dateTime;
    private $reasonCode;

    public function __construct(\BolCom\RetailerApi\Model\Order\OrderItemId $orderItemId, ?\BolCom\RetailerApi\Model\DateTime $dateTime, ?\BolCom\RetailerApi\Model\Order\CancellationReason $reasonCode)
    {
        $this->orderItemId = $orderItemId;
        $this->dateTime = $dateTime;
        $this->reasonCode = $reasonCode;
    }

    public function orderItemId(): \BolCom\RetailerApi\Model\Order\OrderItemId
    {
        return $this->orderItemId;
    }

    public function dateTime(): ?\BolCom\RetailerApi\Model\DateTime
    {
        return $this->dateTime;
    }

    public function reasonCode(): ?\BolCom\RetailerApi\Model\Order\CancellationReason
    {
        return $this->reasonCode;
    }

    public function withOrderItemId(\BolCom\RetailerApi\Model\Order\OrderItemId $orderItemId): CancelOrder
    {
        return new self($orderItemId, $this->dateTime, $this->reasonCode);
    }

    public function withDateTime(?\BolCom\RetailerApi\Model\DateTime $dateTime): CancelOrder
    {
        return new self($this->orderItemId, $dateTime, $this->reasonCode);
    }

    public function withReasonCode(?\BolCom\RetailerApi\Model\Order\CancellationReason $reasonCode): CancelOrder
    {
        return new self($this->orderItemId, $this->dateTime, $reasonCode);
    }
}
