<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Order\Command;

final class ShipOrderItem extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    public const MESSAGE_NAME = 'BolCom\RetailerApi\Model\Order\Command\ShipOrderItem';

    protected $messageName = self::MESSAGE_NAME;

    public function orderItemId(): \BolCom\RetailerApi\Model\Order\OrderItemId
    {
        return \BolCom\RetailerApi\Model\Order\OrderItemId::fromString($this->payload['orderItemId']);
    }

    public function shipmentReference(): ?string
    {
        return $this->payload['shipmentReference'] ?? null;
    }

    public function shippingLabelCode(): ?string
    {
        return $this->payload['shippingLabelCode'] ?? null;
    }

    public function transport(): ?\BolCom\RetailerApi\Model\Transport\TransportInstruction
    {
        return isset($this->payload['transport']) ? \BolCom\RetailerApi\Model\Transport\TransportInstruction::fromArray($this->payload['transport']) : null;
    }

    public static function with(\BolCom\RetailerApi\Model\Order\OrderItemId $orderItemId, ?string $shipmentReference, ?string $shippingLabelCode, ?\BolCom\RetailerApi\Model\Transport\TransportInstruction $transport): ShipOrderItem
    {
        return new self([
            'orderItemId' => $orderItemId->toString(),
            'shipmentReference' => $shipmentReference,
            'shippingLabelCode' => $shippingLabelCode,
            'transport' => null === $transport ? null : $transport->toArray(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (! isset($payload['orderItemId']) || ! \is_string($payload['orderItemId'])) {
            throw new \InvalidArgumentException("Key 'orderItemId' is missing in payload or is not a string");
        }

        if (isset($payload['shipmentReference']) && ! \is_string($payload['shipmentReference'])) {
            throw new \InvalidArgumentException("Value for 'shipmentReference' is not a string in payload");
        }

        if (isset($payload['shippingLabelCode']) && ! \is_string($payload['shippingLabelCode'])) {
            throw new \InvalidArgumentException("Value for 'shippingLabelCode' is not a string in payload");
        }

        if (isset($payload['transport']) && ! \is_array($payload['transport'])) {
            throw new \InvalidArgumentException("Value for 'transport' is not an array in payload");
        }

        $this->payload = $payload;
    }
}
