<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Rma\Query;

final class GetAllReturns
{
    private $page;
    private $handled;
    private $shipmentsMethod;

    public function __construct(int $page, bool $handled, \BolCom\RetailerApi\Model\FulfilmentMethod $shipmentsMethod)
    {
        $this->page = $page;
        $this->handled = $handled;
        $this->shipmentsMethod = $shipmentsMethod;
    }

    public function page(): int
    {
        return $this->page;
    }

    public function handled(): bool
    {
        return $this->handled;
    }

    public function shipmentsMethod(): \BolCom\RetailerApi\Model\FulfilmentMethod
    {
        return $this->shipmentsMethod;
    }

    public function withPage(int $page): GetAllReturns
    {
        return new self($page, $this->handled, $this->shipmentsMethod);
    }

    public function withHandled(bool $handled): GetAllReturns
    {
        return new self($this->page, $handled, $this->shipmentsMethod);
    }

    public function withShipmentsMethod(\BolCom\RetailerApi\Model\FulfilmentMethod $shipmentsMethod): GetAllReturns
    {
        return new self($this->page, $this->handled, $shipmentsMethod);
    }
}
