<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Rma\Query;

final class GetReturn extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    const MESSAGE_NAME = 'BolCom\RetailerApi\Model\Rma\Query\GetReturn';

    protected $messageName = self::MESSAGE_NAME;

    public function rmaId(): \BolCom\RetailerApi\Model\Rma\RmaId
    {
        return \BolCom\RetailerApi\Model\Rma\RmaId::fromScalar($this->payload['rmaId']);
    }

    public static function with(\BolCom\RetailerApi\Model\Rma\RmaId $rmaId): GetReturn
    {
        return new self([
            'rmaId' => $rmaId->toScalar(),
        ]);
    }

    protected function setPayload(array $payload)
    {
        if (! isset($payload['rmaId']) || ! \is_int($payload['rmaId'])) {
            throw new \InvalidArgumentException("Key 'rmaId' is missing in payload or is not a int");
        }

        $this->payload = $payload;
    }
}
