<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Transport\Query;

final class GetShippingLabel extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    const MESSAGE_NAME = 'BolCom\RetailerApi\Model\Transport\Query\GetShippingLabel';

    protected $messageName = self::MESSAGE_NAME;

    public function transportId(): \BolCom\RetailerApi\Model\Transport\TransportId
    {
        return \BolCom\RetailerApi\Model\Transport\TransportId::fromScalar($this->payload['transportId']);
    }

    public static function with(\BolCom\RetailerApi\Model\Transport\TransportId $transportId): GetShippingLabel
    {
        return new self([
            'transportId' => $transportId->toScalar(),
        ]);
    }

    protected function setPayload(array $payload)
    {
        if (! isset($payload['transportId']) || ! \is_int($payload['transportId'])) {
            throw new \InvalidArgumentException("Key 'transportId' is missing in payload or is not a int");
        }

        $this->payload = $payload;
    }
}
