<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Commission\Query;

final class GetCommissionList extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    public const MESSAGE_NAME = 'BolCom\RetailerApi\Model\Commission\Query\GetCommissionList';

    protected $messageName = self::MESSAGE_NAME;

    public function commissionQueries(): array
    {
        $__returnValue = [];

        foreach ($this->payload['commissionQueries'] as $__value) {
            $__returnValue[] = \BolCom\RetailerApi\Model\Commission\CommissionQuery::fromArray($__value);
        }

        return $__returnValue;
    }

    public static function with(\BolCom\RetailerApi\Model\Commission\CommissionQuery ...$commissionQueries): GetCommissionList
    {
        return new self([
            'commissionQueries' => $commissionQueries,
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (! isset($payload['commissionQueries'])) {
            throw new \InvalidArgumentException("Key 'commissionQueries' is missing in payload");
        }

        $this->payload = $payload;
    }
}
