<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Commission\Query;

final class GetCommissionList extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    const MESSAGE_NAME = 'BolCom\RetailerApi\Model\Commission\Query\GetCommissionList';

    protected $messageName = self::MESSAGE_NAME;

    /**
     * @return \BolCom\RetailerApi\Model\Commission\CommissionQuery[]
     */
    public function commissionQueries(): array
    {
        $__returnValue = [];

        foreach ($this->payload['commissionQueries'] as $__value) {
            $__returnValue[] = \BolCom\RetailerApi\Model\Commission\CommissionQuery::fromArray($__value);
        }

        return $__returnValue;
    }

        /**
     * @param \BolCom\RetailerApi\Model\Commission\CommissionQuery[]|null $commissionQueries
     */
public static function with(\BolCom\RetailerApi\Model\Commission\CommissionQuery ...$commissionQueries): GetCommissionList
    {
        $__array_commissionQueries = [];

        foreach ($commissionQueries as $__value) {
            $__array_commissionQueries[] = $__value->toArray();
        }

        return new self([
            'commissionQueries' => $__array_commissionQueries,
        ]);
    }

    protected function setPayload(array $payload)
    {
        if (! isset($payload['commissionQueries']) || ! \is_array($payload['commissionQueries'])) {
            throw new \InvalidArgumentException("Key 'commissionQueries' is missing in payload or is not an array");
        }

        foreach ($payload['commissionQueries'] as $__value) {
            if (! \is_array($__value)) {
                throw new \InvalidArgumentException("Key 'commissionQueries' is not an array of arrays in payload");
            }
        }

        $this->payload = $payload;
    }
}
