<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\ShippingLabel;

final class ShippingLabelPdfList
{
    private $pdfs;

    /**
     * @param \BolCom\RetailerApi\Model\ShippingLabel\ShippingLabelPdf[]|null $pdfs
     */
    public function __construct(ShippingLabelPdf ...$pdfs)
    {
        $this->pdfs = $pdfs;
    }

    /**
     * @return \BolCom\RetailerApi\Model\ShippingLabel\ShippingLabelPdf[]
     */
    public function pdfs(): array
    {
        return $this->pdfs;
    }

    /**
     * @param \BolCom\RetailerApi\Model\ShippingLabel\ShippingLabelPdf[]|null $pdfs
     * @return \BolCom\RetailerApi\Model\ShippingLabel\ShippingLabelPdfList
     */
    public function withPdfs(array $pdfs): ShippingLabelPdfList
    {
        return new self(...$pdfs);
    }

    public static function fromArray(array $data): ShippingLabelPdfList
    {
        if (! isset($data['pdfs']) || ! \is_array($data['pdfs'])) {
            throw new \InvalidArgumentException("Key 'pdfs' is missing in data array or is not an array");
        }

        $pdfs = [];

        foreach ($data['pdfs'] as $__value) {
            if (! \is_string($__value)) {
                throw new \InvalidArgumentException("Value for 'pdfs' in data array is not an array of string");
            }

            $pdfs[] = ShippingLabelPdf::fromString($__value);
        }

        return new self(...$pdfs);
    }
}
