<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\ShippingLabel;

final class ShippingLabelList
{
    private $purchasableShippingLabels;

    /**
     * @param \BolCom\RetailerApi\Model\ShippingLabel\ShippingLabel[]|null $purchasableShippingLabels
     */
    public function __construct(ShippingLabel ...$purchasableShippingLabels)
    {
        $this->purchasableShippingLabels = $purchasableShippingLabels;
    }

    /**
     * @return \BolCom\RetailerApi\Model\ShippingLabel\ShippingLabel[]
     */
    public function purchasableShippingLabels(): array
    {
        return $this->purchasableShippingLabels;
    }

    /**
     * @param \BolCom\RetailerApi\Model\ShippingLabel\ShippingLabel[]|null $purchasableShippingLabels
     * @return \BolCom\RetailerApi\Model\ShippingLabel\ShippingLabelList
     */
    public function withPurchasableShippingLabels(array $purchasableShippingLabels): ShippingLabelList
    {
        return new self(...$purchasableShippingLabels);
    }

    public static function fromArray(array $data): ShippingLabelList
    {
        if (! isset($data['purchasableShippingLabels']) || ! \is_array($data['purchasableShippingLabels'])) {
            throw new \InvalidArgumentException("Key 'purchasableShippingLabels' is missing in data array or is not an array");
        }

        $purchasableShippingLabels = [];

        foreach ($data['purchasableShippingLabels'] as $__value) {
            if (! \is_array($data['purchasableShippingLabels'])) {
                throw new \InvalidArgumentException("Key 'purchasableShippingLabels' in data array or is not an array of arrays");
            }

            $purchasableShippingLabels[] = ShippingLabel::fromArray($__value);
        }

        return new self(...$purchasableShippingLabels);
    }
}
