<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Rma\Command;

final class HandleReturn extends \Prooph\Common\Messaging\Command
{
    use \Prooph\Common\Messaging\PayloadTrait;

    public const MESSAGE_NAME = 'BolCom\RetailerApi\Model\Rma\Command\HandleReturn';

    protected $messageName = self::MESSAGE_NAME;

    public function rmaId(): \BolCom\RetailerApi\Model\Rma\RmaId
    {
        return \BolCom\RetailerApi\Model\Rma\RmaId::fromScalar($this->payload['rmaId']);
    }

    public function handlingResult(): \BolCom\RetailerApi\Model\Rma\HandlingResult
    {
        return \BolCom\RetailerApi\Model\Rma\HandlingResult::fromValue($this->payload['handlingResult']);
    }

    public function quantityReturned(): \BolCom\RetailerApi\Model\Rma\QuantityReturned
    {
        return \BolCom\RetailerApi\Model\Rma\QuantityReturned::fromScalar($this->payload['quantityReturned']);
    }

    public static function with(\BolCom\RetailerApi\Model\Rma\RmaId $rmaId, \BolCom\RetailerApi\Model\Rma\HandlingResult $handlingResult, \BolCom\RetailerApi\Model\Rma\QuantityReturned $quantityReturned): HandleReturn
    {
        return new self([
            'rmaId' => $rmaId->toScalar(),
            'handlingResult' => $handlingResult->value(),
            'quantityReturned' => $quantityReturned->toScalar(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (! isset($payload['rmaId']) || ! \is_int($payload['rmaId'])) {
            throw new \InvalidArgumentException("Key 'rmaId' is missing in payload or is not a int");
        }

        if (! isset($payload['handlingResult']) || ! \is_string($payload['handlingResult'])) {
            throw new \InvalidArgumentException("Key 'handlingResult' is missing in payload or is not a string");
        }

        if (! isset($payload['quantityReturned']) || ! \is_int($payload['quantityReturned'])) {
            throw new \InvalidArgumentException("Key 'quantityReturned' is missing in payload or is not a int");
        }

        $this->payload = $payload;
    }
}
