<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Invoice;

final class Period
{
    private $value;

    public function __construct(string $value)
    {
        if (!\BolCom\RetailerApi\Model\Assert\AssertDateRange::assert($value)) {
            throw new \InvalidArgumentException('Could not create period');
        }

        $this->value = $value;
    }

    public function value(): string
    {
        return $this->value;
    }

    public static function fromString(string $period): Period
    {
        return new self($period);
    }

    public function toString(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}
