<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Inventory;

final class InventoryOffer
{
    private $ean;
    private $bsku;
    private $gradedStock;
    private $regularStock;
    private $title;

    public function __construct(\BolCom\RetailerApi\Model\Offer\Ean $ean, string $bsku, int $gradedStock, int $regularStock, \BolCom\RetailerApi\Model\Offer\Title $title)
    {
        $this->ean = $ean;
        $this->bsku = $bsku;
        $this->gradedStock = $gradedStock;
        $this->regularStock = $regularStock;
        $this->title = $title;
    }

    public function ean(): \BolCom\RetailerApi\Model\Offer\Ean
    {
        return $this->ean;
    }

    public function bsku(): string
    {
        return $this->bsku;
    }

    public function gradedStock(): int
    {
        return $this->gradedStock;
    }

    public function regularStock(): int
    {
        return $this->regularStock;
    }

    public function title(): \BolCom\RetailerApi\Model\Offer\Title
    {
        return $this->title;
    }

    public function withEan(\BolCom\RetailerApi\Model\Offer\Ean $ean): InventoryOffer
    {
        return new self($ean, $this->bsku, $this->gradedStock, $this->regularStock, $this->title);
    }

    public function withBsku(string $bsku): InventoryOffer
    {
        return new self($this->ean, $bsku, $this->gradedStock, $this->regularStock, $this->title);
    }

    public function withGradedStock(int $gradedStock): InventoryOffer
    {
        return new self($this->ean, $this->bsku, $gradedStock, $this->regularStock, $this->title);
    }

    public function withRegularStock(int $regularStock): InventoryOffer
    {
        return new self($this->ean, $this->bsku, $this->gradedStock, $regularStock, $this->title);
    }

    public function withTitle(\BolCom\RetailerApi\Model\Offer\Title $title): InventoryOffer
    {
        return new self($this->ean, $this->bsku, $this->gradedStock, $this->regularStock, $title);
    }

    public function toArray(): array
    {
        return [
            'ean' => $this->ean->toString(),
            'bsku' => $this->bsku,
            'gradedStock' => $this->gradedStock,
            'regularStock' => $this->regularStock,
            'title' => $this->title->toString(),
        ];
    }

    public static function fromArray(array $data): InventoryOffer
    {
        if (! isset($data['ean']) || ! \is_string($data['ean'])) {
            throw new \InvalidArgumentException("Key 'ean' is missing in data array or is not a string");
        }

        $ean = \BolCom\RetailerApi\Model\Offer\Ean::fromString($data['ean']);

        if (! isset($data['bsku']) || ! \is_string($data['bsku'])) {
            throw new \InvalidArgumentException("Key 'bsku' is missing in data array or is not a string");
        }

        $bsku = $data['bsku'];

        if (! isset($data['gradedStock']) || ! \is_int($data['gradedStock'])) {
            throw new \InvalidArgumentException("Key 'gradedStock' is missing in data array or is not a int");
        }

        $gradedStock = $data['gradedStock'];

        if (! isset($data['regularStock']) || ! \is_int($data['regularStock'])) {
            throw new \InvalidArgumentException("Key 'regularStock' is missing in data array or is not a int");
        }

        $regularStock = $data['regularStock'];

        if (! isset($data['title']) || ! \is_string($data['title'])) {
            throw new \InvalidArgumentException("Key 'title' is missing in data array or is not a string");
        }

        $title = \BolCom\RetailerApi\Model\Offer\Title::fromString($data['title']);

        return new self(
            $ean,
            $bsku,
            $gradedStock,
            $regularStock,
            $title
        );
    }
}
