<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Offer\Query;

final class GetOfferCsv extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    const MESSAGE_NAME = 'BolCom\RetailerApi\Model\Offer\Query\GetOfferCsv';

    protected $messageName = self::MESSAGE_NAME;

    public function filename(): string
    {
        return $this->payload['filename'];
    }

    public static function with(string $filename): GetOfferCsv
    {
        return new self([
            'filename' => $filename,
        ]);
    }

    protected function setPayload(array $payload)
    {
        if (! isset($payload['filename']) || ! \is_string($payload['filename'])) {
            throw new \InvalidArgumentException("Key 'filename' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
