<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Offer\Query;

final class GetOffer
{
    private $retailerOfferIdentifier;

    public function __construct(\BolCom\RetailerApi\Model\Offer\RetailerOfferIdentifier $retailerOfferIdentifier)
    {
        $this->retailerOfferIdentifier = $retailerOfferIdentifier;
    }

    public function retailerOfferIdentifier(): \BolCom\RetailerApi\Model\Offer\RetailerOfferIdentifier
    {
        return $this->retailerOfferIdentifier;
    }

    public function withRetailerOfferIdentifier(\BolCom\RetailerApi\Model\Offer\RetailerOfferIdentifier $retailerOfferIdentifier): GetOffer
    {
        return new self($retailerOfferIdentifier);
    }
}
