<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\ShippingLabel\Query;

final class GetShippingLabels
{
    private $orderItemId;

    public function __construct(\BolCom\RetailerApi\Model\Order\OrderItemId $orderItemId)
    {
        $this->orderItemId = $orderItemId;
    }

    public function orderItemId(): \BolCom\RetailerApi\Model\Order\OrderItemId
    {
        return $this->orderItemId;
    }

    public function withOrderItemId(\BolCom\RetailerApi\Model\Order\OrderItemId $orderItemId): GetShippingLabels
    {
        return new self($orderItemId);
    }
}
