<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Rma;

final class ProcessingResult
{
    public const OPTIONS = [
        'Pending' => 'PENDING',
        'Accepted' => 'ACCEPTED',
        'Rejected' => 'REJECTED',
    ];

    public const Pending = 'PENDING';
    public const Accepted = 'ACCEPTED';
    public const Rejected = 'REJECTED';

    private $name;
    private $value;

    private function __construct(string $name)
    {
        $this->name = $name;
        $this->value = self::OPTIONS[$name];
    }

    public static function pending(): self
    {
        return new self('Pending');
    }

    public static function accepted(): self
    {
        return new self('Accepted');
    }

    public static function rejected(): self
    {
        return new self('Rejected');
    }

    public static function fromName(string $value): self
    {
        if (! isset(self::OPTIONS[$value])) {
            throw new \InvalidArgumentException('Unknown enum name given');
        }

        return self::{$value}();
    }

    public static function fromValue($value): self
    {
        foreach (self::OPTIONS as $name => $v) {
            if ($v === $value) {
                return self::{$name}();
            }
        }

        throw new \InvalidArgumentException('Unknown enum value given');
    }

    public function equals(ProcessingResult $other): bool
    {
        return \get_class($this) === \get_class($other) && $this->name === $other->name;
    }

    public function name(): string
    {
        return $this->name;
    }

    public function value()
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function toString(): string
    {
        return $this->name;
    }
}
