<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Rma;

final class ReturnItem
{
    private $rmaId;
    private $orderId;
    private $ean;
    private $title;
    private $quantity;
    private $registrationDateTime;
    private $returnReason;
    private $returnReasonComments;
    private $customerDetails;
    private $fulfilmentMethod;
    private $handled;
    private $trackAndTrace;
    private $handlingResult;
    private $processingResult;
    private $processingDateTime;

    public function __construct(RmaId $rmaId, \BolCom\RetailerApi\Model\Order\OrderId $orderId, \BolCom\RetailerApi\Model\Offer\Ean $ean, string $title, int $quantity, \BolCom\RetailerApi\Model\DateTime $registrationDateTime, string $returnReason, string $returnReasonComments = null, \BolCom\RetailerApi\Model\Customer\CustomerDetails $customerDetails = null, \BolCom\RetailerApi\Model\Offer\FulfilmentMethod $fulfilmentMethod, bool $handled, \BolCom\RetailerApi\Model\Transport\TrackAndTrace $trackAndTrace = null, HandlingResult $handlingResult = null, ProcessingResult $processingResult = null, \BolCom\RetailerApi\Model\DateTime $processingDateTime = null)
    {
        $this->rmaId = $rmaId;
        $this->orderId = $orderId;
        $this->ean = $ean;
        $this->title = $title;
        $this->quantity = $quantity;
        $this->registrationDateTime = $registrationDateTime;
        $this->returnReason = $returnReason;
        $this->returnReasonComments = $returnReasonComments;
        $this->customerDetails = $customerDetails;
        $this->fulfilmentMethod = $fulfilmentMethod;
        $this->handled = $handled;
        $this->trackAndTrace = $trackAndTrace;
        $this->handlingResult = $handlingResult;
        $this->processingResult = $processingResult;
        $this->processingDateTime = $processingDateTime;
    }

    public function rmaId(): RmaId
    {
        return $this->rmaId;
    }

    public function orderId(): \BolCom\RetailerApi\Model\Order\OrderId
    {
        return $this->orderId;
    }

    public function ean(): \BolCom\RetailerApi\Model\Offer\Ean
    {
        return $this->ean;
    }

    public function title(): string
    {
        return $this->title;
    }

    public function quantity(): int
    {
        return $this->quantity;
    }

    public function registrationDateTime(): \BolCom\RetailerApi\Model\DateTime
    {
        return $this->registrationDateTime;
    }

    public function returnReason(): string
    {
        return $this->returnReason;
    }

    public function returnReasonComments()
    {
        return $this->returnReasonComments;
    }

    public function customerDetails()
    {
        return $this->customerDetails;
    }

    public function fulfilmentMethod(): \BolCom\RetailerApi\Model\Offer\FulfilmentMethod
    {
        return $this->fulfilmentMethod;
    }

    public function handled(): bool
    {
        return $this->handled;
    }

    public function trackAndTrace()
    {
        return $this->trackAndTrace;
    }

    public function handlingResult()
    {
        return $this->handlingResult;
    }

    public function processingResult()
    {
        return $this->processingResult;
    }

    public function processingDateTime()
    {
        return $this->processingDateTime;
    }

    public function withRmaId(RmaId $rmaId): ReturnItem
    {
        return new self($rmaId, $this->orderId, $this->ean, $this->title, $this->quantity, $this->registrationDateTime, $this->returnReason, $this->returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $this->handled, $this->trackAndTrace, $this->handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withOrderId(\BolCom\RetailerApi\Model\Order\OrderId $orderId): ReturnItem
    {
        return new self($this->rmaId, $orderId, $this->ean, $this->title, $this->quantity, $this->registrationDateTime, $this->returnReason, $this->returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $this->handled, $this->trackAndTrace, $this->handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withEan(\BolCom\RetailerApi\Model\Offer\Ean $ean): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $ean, $this->title, $this->quantity, $this->registrationDateTime, $this->returnReason, $this->returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $this->handled, $this->trackAndTrace, $this->handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withTitle(string $title): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $this->ean, $title, $this->quantity, $this->registrationDateTime, $this->returnReason, $this->returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $this->handled, $this->trackAndTrace, $this->handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withQuantity(int $quantity): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $this->ean, $this->title, $quantity, $this->registrationDateTime, $this->returnReason, $this->returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $this->handled, $this->trackAndTrace, $this->handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withRegistrationDateTime(\BolCom\RetailerApi\Model\DateTime $registrationDateTime): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $this->ean, $this->title, $this->quantity, $registrationDateTime, $this->returnReason, $this->returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $this->handled, $this->trackAndTrace, $this->handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withReturnReason(string $returnReason): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $this->ean, $this->title, $this->quantity, $this->registrationDateTime, $returnReason, $this->returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $this->handled, $this->trackAndTrace, $this->handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withReturnReasonComments(string $returnReasonComments = null): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $this->ean, $this->title, $this->quantity, $this->registrationDateTime, $this->returnReason, $returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $this->handled, $this->trackAndTrace, $this->handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withCustomerDetails(\BolCom\RetailerApi\Model\Customer\CustomerDetails $customerDetails = null): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $this->ean, $this->title, $this->quantity, $this->registrationDateTime, $this->returnReason, $this->returnReasonComments, $customerDetails, $this->fulfilmentMethod, $this->handled, $this->trackAndTrace, $this->handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withFulfilmentMethod(\BolCom\RetailerApi\Model\Offer\FulfilmentMethod $fulfilmentMethod): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $this->ean, $this->title, $this->quantity, $this->registrationDateTime, $this->returnReason, $this->returnReasonComments, $this->customerDetails, $fulfilmentMethod, $this->handled, $this->trackAndTrace, $this->handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withHandled(bool $handled): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $this->ean, $this->title, $this->quantity, $this->registrationDateTime, $this->returnReason, $this->returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $handled, $this->trackAndTrace, $this->handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withTrackAndTrace(\BolCom\RetailerApi\Model\Transport\TrackAndTrace $trackAndTrace = null): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $this->ean, $this->title, $this->quantity, $this->registrationDateTime, $this->returnReason, $this->returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $this->handled, $trackAndTrace, $this->handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withHandlingResult(HandlingResult $handlingResult = null): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $this->ean, $this->title, $this->quantity, $this->registrationDateTime, $this->returnReason, $this->returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $this->handled, $this->trackAndTrace, $handlingResult, $this->processingResult, $this->processingDateTime);
    }

    public function withProcessingResult(ProcessingResult $processingResult = null): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $this->ean, $this->title, $this->quantity, $this->registrationDateTime, $this->returnReason, $this->returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $this->handled, $this->trackAndTrace, $this->handlingResult, $processingResult, $this->processingDateTime);
    }

    public function withProcessingDateTime(\BolCom\RetailerApi\Model\DateTime $processingDateTime = null): ReturnItem
    {
        return new self($this->rmaId, $this->orderId, $this->ean, $this->title, $this->quantity, $this->registrationDateTime, $this->returnReason, $this->returnReasonComments, $this->customerDetails, $this->fulfilmentMethod, $this->handled, $this->trackAndTrace, $this->handlingResult, $this->processingResult, $processingDateTime);
    }

    public static function fromArray(array $data): ReturnItem
    {
        if (! isset($data['rmaId']) || ! \is_int($data['rmaId'])) {
            throw new \InvalidArgumentException("Key 'rmaId' is missing in data array or is not a int");
        }

        $rmaId = RmaId::fromScalar($data['rmaId']);

        if (! isset($data['orderId']) || ! \is_string($data['orderId'])) {
            throw new \InvalidArgumentException("Key 'orderId' is missing in data array or is not a string");
        }

        $orderId = \BolCom\RetailerApi\Model\Order\OrderId::fromString($data['orderId']);

        if (! isset($data['ean']) || ! \is_string($data['ean'])) {
            throw new \InvalidArgumentException("Key 'ean' is missing in data array or is not a string");
        }

        $ean = \BolCom\RetailerApi\Model\Offer\Ean::fromString($data['ean']);

        if (! isset($data['title']) || ! \is_string($data['title'])) {
            throw new \InvalidArgumentException("Key 'title' is missing in data array or is not a string");
        }

        $title = $data['title'];

        if (! isset($data['quantity']) || ! \is_int($data['quantity'])) {
            throw new \InvalidArgumentException("Key 'quantity' is missing in data array or is not a int");
        }

        $quantity = $data['quantity'];

        if (! isset($data['registrationDateTime']) || ! \is_string($data['registrationDateTime'])) {
            throw new \InvalidArgumentException("Key 'registrationDateTime' is missing in data array or is not a string");
        }

        $registrationDateTime = \BolCom\RetailerApi\Model\DateTime::fromString($data['registrationDateTime']);

        if (! isset($data['returnReason']) || ! \is_string($data['returnReason'])) {
            throw new \InvalidArgumentException("Key 'returnReason' is missing in data array or is not a string");
        }

        $returnReason = $data['returnReason'];

        if (isset($data['returnReasonComments'])) {
            if (! \is_string($data['returnReasonComments'])) {
                throw new \InvalidArgumentException("Value for 'returnReasonComments' is not a string in data array");
            }

            $returnReasonComments = $data['returnReasonComments'];
        } else {
            $returnReasonComments = null;
        }

        if (isset($data['customerDetails'])) {
            if (! \is_array($data['customerDetails'])) {
                throw new \InvalidArgumentException("Value for 'customerDetails' is not an array in data array");
            }

            $customerDetails = \BolCom\RetailerApi\Model\Customer\CustomerDetails::fromArray($data['customerDetails']);
        } else {
            $customerDetails = null;
        }

        if (! isset($data['fulfilmentMethod']) || ! \is_string($data['fulfilmentMethod'])) {
            throw new \InvalidArgumentException("Key 'fulfilmentMethod' is missing in data array or is not a string");
        }

        $fulfilmentMethod = \BolCom\RetailerApi\Model\Offer\FulfilmentMethod::fromValue($data['fulfilmentMethod']);

        if (! isset($data['handled']) || ! \is_bool($data['handled'])) {
            throw new \InvalidArgumentException("Key 'handled' is missing in data array or is not a bool");
        }

        $handled = $data['handled'];

        if (isset($data['trackAndTrace'])) {
            if (! \is_string($data['trackAndTrace'])) {
                throw new \InvalidArgumentException("Value for 'trackAndTrace' is not a string in data array");
            }

            $trackAndTrace = \BolCom\RetailerApi\Model\Transport\TrackAndTrace::fromScalar($data['trackAndTrace']);
        } else {
            $trackAndTrace = null;
        }

        if (isset($data['handlingResult'])) {
            if (! \is_string($data['handlingResult'])) {
                throw new \InvalidArgumentException("Value for 'handlingResult' is not a string in data array");
            }

            $handlingResult = HandlingResult::fromValue($data['handlingResult']);
        } else {
            $handlingResult = null;
        }

        if (isset($data['processingResult'])) {
            if (! \is_string($data['processingResult'])) {
                throw new \InvalidArgumentException("Value for 'processingResult' is not a string in data array");
            }

            $processingResult = ProcessingResult::fromValue($data['processingResult']);
        } else {
            $processingResult = null;
        }

        if (isset($data['processingDateTime'])) {
            if (! \is_string($data['processingDateTime'])) {
                throw new \InvalidArgumentException("Value for 'processingDateTime' is not a string in data array");
            }

            $processingDateTime = \BolCom\RetailerApi\Model\DateTime::fromString($data['processingDateTime']);
        } else {
            $processingDateTime = null;
        }

        return new self(
            $rmaId,
            $orderId,
            $ean,
            $title,
            $quantity,
            $registrationDateTime,
            $returnReason,
            $returnReasonComments,
            $customerDetails,
            $fulfilmentMethod,
            $handled,
            $trackAndTrace,
            $handlingResult,
            $processingResult,
            $processingDateTime
        );
    }
}
