<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Order;

final class OrderListItem
{
    private $orderId;
    private $orderPlacedDateTime;

    public function __construct(OrderId $orderId, \BolCom\RetailerApi\Model\DateTime $orderPlacedDateTime)
    {
        $this->orderId = $orderId;
        $this->orderPlacedDateTime = $orderPlacedDateTime;
    }

    public function orderId(): OrderId
    {
        return $this->orderId;
    }

    public function orderPlacedDateTime(): \BolCom\RetailerApi\Model\DateTime
    {
        return $this->orderPlacedDateTime;
    }

    public function withOrderId(OrderId $orderId): OrderListItem
    {
        return new self($orderId, $this->orderPlacedDateTime);
    }

    public function withOrderPlacedDateTime(\BolCom\RetailerApi\Model\DateTime $orderPlacedDateTime): OrderListItem
    {
        return new self($this->orderId, $orderPlacedDateTime);
    }

    public static function fromArray(array $data): OrderListItem
    {
        if (! isset($data['orderId']) || ! \is_string($data['orderId'])) {
            throw new \InvalidArgumentException("Key 'orderId' is missing in data array or is not a string");
        }

        $orderId = OrderId::fromString($data['orderId']);

        if (! isset($data['orderPlacedDateTime']) || ! \is_string($data['orderPlacedDateTime'])) {
            throw new \InvalidArgumentException("Key 'orderPlacedDateTime' is missing in data array or is not a string");
        }

        $orderPlacedDateTime = \BolCom\RetailerApi\Model\DateTime::fromString($data['orderPlacedDateTime']);

        return new self($orderId, $orderPlacedDateTime);
    }
}
