<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Order;

final class OrderProduct
{
    private $ean;
    private $title;

    public function __construct(\BolCom\RetailerApi\Model\Offer\Ean $ean, string $title)
    {
        $this->ean = $ean;
        $this->title = $title;
    }

    public function ean(): \BolCom\RetailerApi\Model\Offer\Ean
    {
        return $this->ean;
    }

    public function title(): string
    {
        return $this->title;
    }

    public function withEan(\BolCom\RetailerApi\Model\Offer\Ean $ean): OrderProduct
    {
        return new self($ean, $this->title);
    }

    public function withTitle(string $title): OrderProduct
    {
        return new self($this->ean, $title);
    }

    public static function fromArray(array $data): OrderProduct
    {
        if (! isset($data['ean']) || ! \is_string($data['ean'])) {
            throw new \InvalidArgumentException("Key 'ean' is missing in data array or is not a string");
        }

        $ean = \BolCom\RetailerApi\Model\Offer\Ean::fromString($data['ean']);

        if (! isset($data['title']) || ! \is_string($data['title'])) {
            throw new \InvalidArgumentException("Key 'title' is missing in data array or is not a string");
        }

        $title = $data['title'];

        return new self($ean, $title);
    }
}
