<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Order;

final class OrderList
{
    private $orders;

    public function __construct(Order ...$orders)
    {
        $this->orders = $orders;
    }

    /**
     * @return \BolCom\RetailerApi\Model\Order\Order[]
     */
    public function orders(): array
    {
        return $this->orders;
    }

    public function withOrders(array $orders): OrderList
    {
        return new self(...$orders);
    }

    public static function fromArray(array $data): OrderList
    {
        if (! isset($data['orders']) || ! \is_array($data['orders'])) {
            throw new \InvalidArgumentException("Key 'orders' is missing in data array or is not an array");
        }

        $orders = [];

        foreach ($data['orders'] as $__value) {
            if (! \is_array($data['orders'])) {
                throw new \InvalidArgumentException("Key 'orders' in data array or is not an array of arrays");
            }

            $orders[] = Order::fromArray($__value);
        }

        return new self(...$orders);
    }
}
