<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Offer;

final class DeliveryCode
{
    const OPTIONS = [
        'DC24uurs23' => '24uurs-23',
        'DC24uurs22' => '24uurs-22',
        'DC24uurs21' => '24uurs-21',
        'DC24uurs20' => '24uurs-20',
        'DC24uurs19' => '24uurs-19',
        'DC24uurs18' => '24uurs-18',
        'DC24uurs17' => '24uurs-17',
        'DC24uurs16' => '24uurs-16',
        'DC24uurs15' => '24uurs-15',
        'DC24uurs14' => '24uurs-14',
        'DC24uurs13' => '24uurs-13',
        'DC24uurs12' => '24uurs-12',
        'DC12d' => '1-2d',
        'DC23d' => '2-3d',
        'DC34d' => '3-4d',
        'DC35d' => '3-5d',
        'DC48d' => '4-8d',
        'DC18d' => '1-8d',
        'DCMijnLeverbelofte' => 'MijnLeverbelofte',
    ];

    const DC24uurs23 = '24uurs-23';
    const DC24uurs22 = '24uurs-22';
    const DC24uurs21 = '24uurs-21';
    const DC24uurs20 = '24uurs-20';
    const DC24uurs19 = '24uurs-19';
    const DC24uurs18 = '24uurs-18';
    const DC24uurs17 = '24uurs-17';
    const DC24uurs16 = '24uurs-16';
    const DC24uurs15 = '24uurs-15';
    const DC24uurs14 = '24uurs-14';
    const DC24uurs13 = '24uurs-13';
    const DC24uurs12 = '24uurs-12';
    const DC12d = '1-2d';
    const DC23d = '2-3d';
    const DC34d = '3-4d';
    const DC35d = '3-5d';
    const DC48d = '4-8d';
    const DC18d = '1-8d';
    const DCMijnLeverbelofte = 'MijnLeverbelofte';

    private $name;
    private $value;

    private function __construct(string $name)
    {
        $this->name = $name;
        $this->value = self::OPTIONS[$name];
    }

    public static function dC24uurs23(): self
    {
        return new self('DC24uurs23');
    }

    public static function dC24uurs22(): self
    {
        return new self('DC24uurs22');
    }

    public static function dC24uurs21(): self
    {
        return new self('DC24uurs21');
    }

    public static function dC24uurs20(): self
    {
        return new self('DC24uurs20');
    }

    public static function dC24uurs19(): self
    {
        return new self('DC24uurs19');
    }

    public static function dC24uurs18(): self
    {
        return new self('DC24uurs18');
    }

    public static function dC24uurs17(): self
    {
        return new self('DC24uurs17');
    }

    public static function dC24uurs16(): self
    {
        return new self('DC24uurs16');
    }

    public static function dC24uurs15(): self
    {
        return new self('DC24uurs15');
    }

    public static function dC24uurs14(): self
    {
        return new self('DC24uurs14');
    }

    public static function dC24uurs13(): self
    {
        return new self('DC24uurs13');
    }

    public static function dC24uurs12(): self
    {
        return new self('DC24uurs12');
    }

    public static function dC12d(): self
    {
        return new self('DC12d');
    }

    public static function dC23d(): self
    {
        return new self('DC23d');
    }

    public static function dC34d(): self
    {
        return new self('DC34d');
    }

    public static function dC35d(): self
    {
        return new self('DC35d');
    }

    public static function dC48d(): self
    {
        return new self('DC48d');
    }

    public static function dC18d(): self
    {
        return new self('DC18d');
    }

    public static function dCMijnLeverbelofte(): self
    {
        return new self('DCMijnLeverbelofte');
    }

    public static function fromName(string $value): self
    {
        if (! isset(self::OPTIONS[$value])) {
            throw new \InvalidArgumentException('Unknown enum name given');
        }

        return self::{$value}();
    }

    public static function fromValue($value): self
    {
        foreach (self::OPTIONS as $name => $v) {
            if ($v === $value) {
                return self::{$name}();
            }
        }

        throw new \InvalidArgumentException('Unknown enum value given');
    }

    public function equals(DeliveryCode $other): bool
    {
        return \get_class($this) === \get_class($other) && $this->name === $other->name;
    }

    public function name(): string
    {
        return $this->name;
    }

    public function value()
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function toString(): string
    {
        return $this->name;
    }
}
