<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Offer;

final class OfferId
{
    private $uuid;

    public static function generate(): OfferId
    {
        return new self(\Ramsey\Uuid\Uuid::uuid4());
    }

    public static function fromString(string $offerId): OfferId
    {
        return new self(\Ramsey\Uuid\Uuid::fromString($offerId));
    }

    private function __construct(\Ramsey\Uuid\UuidInterface $offerId)
    {
        $this->uuid = $offerId;
    }

    public function toString(): string
    {
        return $this->uuid->toString();
    }

    public function __toString(): string
    {
        return $this->uuid->toString();
    }

    public function equals(OfferId $other): bool
    {
        return $this->uuid->equals($other->uuid);
    }
}
