<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Offer;

final class OfferExportId
{
    private $uuid;

    public static function generate(): OfferExportId
    {
        return new self(\Ramsey\Uuid\Uuid::uuid4());
    }

    public static function fromString(string $offerExportId): OfferExportId
    {
        return new self(\Ramsey\Uuid\Uuid::fromString($offerExportId));
    }

    private function __construct(\Ramsey\Uuid\UuidInterface $offerExportId)
    {
        $this->uuid = $offerExportId;
    }

    public function toString(): string
    {
        return $this->uuid->toString();
    }

    public function __toString(): string
    {
        return $this->uuid->toString();
    }

    public function equals(OfferExportId $other): bool
    {
        return $this->uuid->equals($other->uuid);
    }
}
