<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Offer;

final class RetailerOfferExportList
{
    private $offers;

    /**
     * @param \BolCom\RetailerApi\Model\Offer\RetailerOfferExport[]|null $offers
     */
    public function __construct(RetailerOfferExport ...$offers)
    {
        $this->offers = $offers;
    }

    /**
     * @return \BolCom\RetailerApi\Model\Offer\RetailerOfferExport[]
     */
    public function offers(): array
    {
        return $this->offers;
    }

    /**
     * @param \BolCom\RetailerApi\Model\Offer\RetailerOfferExport[]|null $offers
     * @return \BolCom\RetailerApi\Model\Offer\RetailerOfferExportList
     */
    public function withOffers(array $offers): RetailerOfferExportList
    {
        return new self(...$offers);
    }

    public function toArray(): array
    {
        $offers = [];

        foreach ($this->offers as $__value) {
            $offers[] = $__value->toArray();
        }

        return $offers;
    }

    public static function fromArray(array $data): RetailerOfferExportList
    {
        $offers = [];
        foreach ($data as $__value) {
            $offers[] = RetailerOfferExport::fromArray($__value);
        }
        return new self(...$offers);
    }
}
