<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Offer;

final class RetailerOffer
{
    private $ean;
    private $condition;
    private $price;
    private $deliveryCode;
    private $quantityInStock;
    private $unreservedStock;
    private $publish;
    private $referenceCode;
    private $description;
    private $title;
    private $fulfilmentMethod;
    private $status;

    public function __construct(Ean $ean, Condition $condition, Price $price, DeliveryCode $deliveryCode, QuantityInStock $quantityInStock, UnreservedStock $unreservedStock, bool $publish, ReferenceCode $referenceCode, Description $description, Title $title, \BolCom\RetailerApi\Model\Shipment\FulfilmentMethod $fulfilmentMethod, RetailerOfferStatus $status)
    {
        $this->ean = $ean;
        $this->condition = $condition;
        $this->price = $price;
        $this->deliveryCode = $deliveryCode;
        $this->quantityInStock = $quantityInStock;
        $this->unreservedStock = $unreservedStock;
        $this->publish = $publish;
        $this->referenceCode = $referenceCode;
        $this->description = $description;
        $this->title = $title;
        $this->fulfilmentMethod = $fulfilmentMethod;
        $this->status = $status;
    }

    public function ean(): Ean
    {
        return $this->ean;
    }

    public function condition(): Condition
    {
        return $this->condition;
    }

    public function price(): Price
    {
        return $this->price;
    }

    public function deliveryCode(): DeliveryCode
    {
        return $this->deliveryCode;
    }

    public function quantityInStock(): QuantityInStock
    {
        return $this->quantityInStock;
    }

    public function unreservedStock(): UnreservedStock
    {
        return $this->unreservedStock;
    }

    public function publish(): bool
    {
        return $this->publish;
    }

    public function referenceCode(): ReferenceCode
    {
        return $this->referenceCode;
    }

    public function description(): Description
    {
        return $this->description;
    }

    public function title(): Title
    {
        return $this->title;
    }

    public function fulfilmentMethod(): \BolCom\RetailerApi\Model\Shipment\FulfilmentMethod
    {
        return $this->fulfilmentMethod;
    }

    public function status(): RetailerOfferStatus
    {
        return $this->status;
    }

    public function withEan(Ean $ean): RetailerOffer
    {
        return new self($ean, $this->condition, $this->price, $this->deliveryCode, $this->quantityInStock, $this->unreservedStock, $this->publish, $this->referenceCode, $this->description, $this->title, $this->fulfilmentMethod, $this->status);
    }

    public function withCondition(Condition $condition): RetailerOffer
    {
        return new self($this->ean, $condition, $this->price, $this->deliveryCode, $this->quantityInStock, $this->unreservedStock, $this->publish, $this->referenceCode, $this->description, $this->title, $this->fulfilmentMethod, $this->status);
    }

    public function withPrice(Price $price): RetailerOffer
    {
        return new self($this->ean, $this->condition, $price, $this->deliveryCode, $this->quantityInStock, $this->unreservedStock, $this->publish, $this->referenceCode, $this->description, $this->title, $this->fulfilmentMethod, $this->status);
    }

    public function withDeliveryCode(DeliveryCode $deliveryCode): RetailerOffer
    {
        return new self($this->ean, $this->condition, $this->price, $deliveryCode, $this->quantityInStock, $this->unreservedStock, $this->publish, $this->referenceCode, $this->description, $this->title, $this->fulfilmentMethod, $this->status);
    }

    public function withQuantityInStock(QuantityInStock $quantityInStock): RetailerOffer
    {
        return new self($this->ean, $this->condition, $this->price, $this->deliveryCode, $quantityInStock, $this->unreservedStock, $this->publish, $this->referenceCode, $this->description, $this->title, $this->fulfilmentMethod, $this->status);
    }

    public function withUnreservedStock(UnreservedStock $unreservedStock): RetailerOffer
    {
        return new self($this->ean, $this->condition, $this->price, $this->deliveryCode, $this->quantityInStock, $unreservedStock, $this->publish, $this->referenceCode, $this->description, $this->title, $this->fulfilmentMethod, $this->status);
    }

    public function withPublish(bool $publish): RetailerOffer
    {
        return new self($this->ean, $this->condition, $this->price, $this->deliveryCode, $this->quantityInStock, $this->unreservedStock, $publish, $this->referenceCode, $this->description, $this->title, $this->fulfilmentMethod, $this->status);
    }

    public function withReferenceCode(ReferenceCode $referenceCode): RetailerOffer
    {
        return new self($this->ean, $this->condition, $this->price, $this->deliveryCode, $this->quantityInStock, $this->unreservedStock, $this->publish, $referenceCode, $this->description, $this->title, $this->fulfilmentMethod, $this->status);
    }

    public function withDescription(Description $description): RetailerOffer
    {
        return new self($this->ean, $this->condition, $this->price, $this->deliveryCode, $this->quantityInStock, $this->unreservedStock, $this->publish, $this->referenceCode, $description, $this->title, $this->fulfilmentMethod, $this->status);
    }

    public function withTitle(Title $title): RetailerOffer
    {
        return new self($this->ean, $this->condition, $this->price, $this->deliveryCode, $this->quantityInStock, $this->unreservedStock, $this->publish, $this->referenceCode, $this->description, $title, $this->fulfilmentMethod, $this->status);
    }

    public function withFulfilmentMethod(\BolCom\RetailerApi\Model\Shipment\FulfilmentMethod $fulfilmentMethod): RetailerOffer
    {
        return new self($this->ean, $this->condition, $this->price, $this->deliveryCode, $this->quantityInStock, $this->unreservedStock, $this->publish, $this->referenceCode, $this->description, $this->title, $fulfilmentMethod, $this->status);
    }

    public function withStatus(RetailerOfferStatus $status): RetailerOffer
    {
        return new self($this->ean, $this->condition, $this->price, $this->deliveryCode, $this->quantityInStock, $this->unreservedStock, $this->publish, $this->referenceCode, $this->description, $this->title, $this->fulfilmentMethod, $status);
    }

    public static function fromArray(array $data): RetailerOffer
    {
        if (! isset($data['ean']) || ! \is_string($data['ean'])) {
            throw new \InvalidArgumentException("Key 'ean' is missing in data array or is not a string");
        }

        $ean = Ean::fromString($data['ean']);

        if (! isset($data['condition']) || ! \is_string($data['condition'])) {
            throw new \InvalidArgumentException("Key 'condition' is missing in data array or is not a string");
        }

        $condition = Condition::fromValue($data['condition']);

        if (! isset($data['price']) || (! \is_float($data['price']) && ! \is_int($data['price']))) {
            throw new \InvalidArgumentException("Key 'price' is missing in data array or is not a float");
        }

        $price = Price::fromScalar($data['price']);

        if (! isset($data['deliveryCode']) || ! \is_string($data['deliveryCode'])) {
            throw new \InvalidArgumentException("Key 'deliveryCode' is missing in data array or is not a string");
        }

        $deliveryCode = DeliveryCode::fromValue($data['deliveryCode']);

        if (! isset($data['quantityInStock']) || ! \is_int($data['quantityInStock'])) {
            throw new \InvalidArgumentException("Key 'quantityInStock' is missing in data array or is not a int");
        }

        $quantityInStock = QuantityInStock::fromScalar($data['quantityInStock']);

        if (! isset($data['unreservedStock']) || ! \is_int($data['unreservedStock'])) {
            throw new \InvalidArgumentException("Key 'unreservedStock' is missing in data array or is not a int");
        }

        $unreservedStock = UnreservedStock::fromScalar($data['unreservedStock']);

        if (! isset($data['publish']) || ! \is_bool($data['publish'])) {
            throw new \InvalidArgumentException("Key 'publish' is missing in data array or is not a bool");
        }

        $publish = $data['publish'];

        if (! isset($data['referenceCode']) || ! \is_string($data['referenceCode'])) {
            throw new \InvalidArgumentException("Key 'referenceCode' is missing in data array or is not a string");
        }

        $referenceCode = ReferenceCode::fromString($data['referenceCode']);

        if (! isset($data['description']) || ! \is_string($data['description'])) {
            throw new \InvalidArgumentException("Key 'description' is missing in data array or is not a string");
        }

        $description = Description::fromString($data['description']);

        if (! isset($data['title']) || ! \is_string($data['title'])) {
            throw new \InvalidArgumentException("Key 'title' is missing in data array or is not a string");
        }

        $title = Title::fromString($data['title']);

        if (! isset($data['fulfilmentMethod']) || ! \is_string($data['fulfilmentMethod'])) {
            throw new \InvalidArgumentException("Key 'fulfilmentMethod' is missing in data array or is not a string");
        }

        $fulfilmentMethod = \BolCom\RetailerApi\Model\Shipment\FulfilmentMethod::fromValue($data['fulfilmentMethod']);

        if (! isset($data['status']) || ! \is_array($data['status'])) {
            throw new \InvalidArgumentException("Key 'status' is missing in data array or is not an array");
        }

        $status = RetailerOfferStatus::fromArray($data['status']);

        return new self(
            $ean,
            $condition,
            $price,
            $deliveryCode,
            $quantityInStock,
            $unreservedStock,
            $publish,
            $referenceCode,
            $description,
            $title,
            $fulfilmentMethod,
            $status
        );
    }
}
