<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Offer;

final class RetailerOfferIdentifier
{
    private $ean;
    private $condition;

    public function __construct(\BolCom\RetailerApi\Model\Ean $ean, Condition $condition)
    {
        $this->ean = $ean;
        $this->condition = $condition;
    }

    public function ean(): \BolCom\RetailerApi\Model\Ean
    {
        return $this->ean;
    }

    public function condition(): Condition
    {
        return $this->condition;
    }

    public function withEan(\BolCom\RetailerApi\Model\Ean $ean): RetailerOfferIdentifier
    {
        return new self($ean, $this->condition);
    }

    public function withCondition(Condition $condition): RetailerOfferIdentifier
    {
        return new self($this->ean, $condition);
    }

    public function toArray(): array
    {
        return [
            'ean' => $this->ean->toString(),
            'condition' => $this->condition->name(),
        ];
    }
}
