<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Offer;

final class UnreservedStock
{
    private $value;

    public function __construct(int $value)
    {
        if (!\Assert\Assertion::between($value, 0, 999)) {
            throw new \InvalidArgumentException('');
        }

        $this->value = $value;
    }

    public function value(): int
    {
        return $this->value;
    }

    public static function fromScalar(int $unreservedStock): UnreservedStock
    {
        return new self($unreservedStock);
    }

    public function toScalar(): int
    {
        return $this->value;
    }
}
