<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Shipment\Query;

final class GetShipment
{
    private $shipmentId;

    public function __construct(\BolCom\RetailerApi\Model\Shipment\ShipmentId $shipmentId)
    {
        $this->shipmentId = $shipmentId;
    }

    public function shipmentId(): \BolCom\RetailerApi\Model\Shipment\ShipmentId
    {
        return $this->shipmentId;
    }

    public function withShipmentId(\BolCom\RetailerApi\Model\Shipment\ShipmentId $shipmentId): GetShipment
    {
        return new self($shipmentId);
    }
}
