<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Inbound\Query;

final class GetInboundList extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    const MESSAGE_NAME = 'BolCom\RetailerApi\Model\Inbound\Query\GetInboundList';

    protected $messageName = self::MESSAGE_NAME;

    public function reference()
    {
        return isset($this->payload['reference']) ? \BolCom\RetailerApi\Model\Inbound\Reference::fromString($this->payload['reference']) : null;
    }

    public function bsku()
    {
        return isset($this->payload['bsku']) ? \BolCom\RetailerApi\Model\Inbound\BSku::fromString($this->payload['bsku']) : null;
    }

    public function creationStart()
    {
        return isset($this->payload['creationStart']) ? \BolCom\RetailerApi\Model\Date::fromString($this->payload['creationStart']) : null;
    }

    public function creationEnd()
    {
        return isset($this->payload['creationEnd']) ? \BolCom\RetailerApi\Model\Date::fromString($this->payload['creationEnd']) : null;
    }

    public function state()
    {
        return isset($this->payload['state']) ? \BolCom\RetailerApi\Model\Inbound\State::fromValue($this->payload['state']) : null;
    }

    public function page()
    {
        return $this->payload['page'] ?? null;
    }

    public static function with(\BolCom\RetailerApi\Model\Inbound\Reference $reference = null, \BolCom\RetailerApi\Model\Inbound\BSku $bsku = null, \BolCom\RetailerApi\Model\Date $creationStart = null, \BolCom\RetailerApi\Model\Date $creationEnd = null, \BolCom\RetailerApi\Model\Inbound\State $state = null, int $page = null): GetInboundList
    {
        return new self([
            'reference' => null === $reference ? null : $reference->toString(),
            'bsku' => null === $bsku ? null : $bsku->toString(),
            'creationStart' => null === $creationStart ? null : $creationStart->toString(),
            'creationEnd' => null === $creationEnd ? null : $creationEnd->toString(),
            'state' => null === $state ? null : $state->value(),
            'page' => $page,
        ]);
    }

    protected function setPayload(array $payload)
    {
        if (isset($payload['reference']) && ! \is_string($payload['reference'])) {
            throw new \InvalidArgumentException("Value for 'reference' is not a string in payload");
        }

        if (isset($payload['bsku']) && ! \is_string($payload['bsku'])) {
            throw new \InvalidArgumentException("Value for 'bsku' is not a string in payload");
        }

        if (isset($payload['creationStart']) && ! \is_string($payload['creationStart'])) {
            throw new \InvalidArgumentException("Value for 'creationStart' is not a string in payload");
        }

        if (isset($payload['creationEnd']) && ! \is_string($payload['creationEnd'])) {
            throw new \InvalidArgumentException("Value for 'creationEnd' is not a string in payload");
        }

        if (isset($payload['state']) && ! \is_string($payload['state'])) {
            throw new \InvalidArgumentException("Value for 'state' is not a string in payload");
        }

        if (isset($payload['page']) && ! \is_int($payload['page'])) {
            throw new \InvalidArgumentException("Value for 'page' is not a int in payload");
        }

        $this->payload = $payload;
    }
}
