<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Transport\Command;

final class AddTransportInformation
{
    private $transportId;
    private $transporterCode;
    private $trackAndTrace;

    public function __construct(TransportId $transportId, TransporterCode $transporterCode, ?TrackAndTrace $trackAndTrace)
    {
        $this->transportId = $transportId;
        $this->transporterCode = $transporterCode;
        $this->trackAndTrace = $trackAndTrace;
    }

    public function transportId(): TransportId
    {
        return $this->transportId;
    }

    public function transporterCode(): TransporterCode
    {
        return $this->transporterCode;
    }

    public function trackAndTrace(): ?TrackAndTrace
    {
        return $this->trackAndTrace;
    }

    public function withTransportId(TransportId $transportId): AddTransportInformation
    {
        return new self($transportId, $this->transporterCode, $this->trackAndTrace);
    }

    public function withTransporterCode(TransporterCode $transporterCode): AddTransportInformation
    {
        return new self($this->transportId, $transporterCode, $this->trackAndTrace);
    }

    public function withTrackAndTrace(?TrackAndTrace $trackAndTrace): AddTransportInformation
    {
        return new self($this->transportId, $this->transporterCode, $trackAndTrace);
    }
}
