<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Transport\Command;

final class AddTransportInformation
{
    private $transportId;
    private $transporterCode;
    private $trackAndTrace;

    public function __construct(\BolCom\RetailerApi\Model\Transport\TransportId $transportId, \BolCom\RetailerApi\Model\Transport\TransporterCode $transporterCode, \BolCom\RetailerApi\Model\Transport\TrackAndTrace $trackAndTrace = null)
    {
        $this->transportId = $transportId;
        $this->transporterCode = $transporterCode;
        $this->trackAndTrace = $trackAndTrace;
    }

    public function transportId(): \BolCom\RetailerApi\Model\Transport\TransportId
    {
        return $this->transportId;
    }

    public function transporterCode(): \BolCom\RetailerApi\Model\Transport\TransporterCode
    {
        return $this->transporterCode;
    }

    public function trackAndTrace()
    {
        return $this->trackAndTrace;
    }

    public function withTransportId(\BolCom\RetailerApi\Model\Transport\TransportId $transportId): AddTransportInformation
    {
        return new self($transportId, $this->transporterCode, $this->trackAndTrace);
    }

    public function withTransporterCode(\BolCom\RetailerApi\Model\Transport\TransporterCode $transporterCode): AddTransportInformation
    {
        return new self($this->transportId, $transporterCode, $this->trackAndTrace);
    }

    public function withTrackAndTrace(\BolCom\RetailerApi\Model\Transport\TrackAndTrace $trackAndTrace = null): AddTransportInformation
    {
        return new self($this->transportId, $this->transporterCode, $trackAndTrace);
    }
}
