<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Transport\Command;

final class GetShippingLabel
{
    private $transportId;

    public function __construct(TransportId $transportId)
    {
        $this->transportId = $transportId;
    }

    public function transportId(): TransportId
    {
        return $this->transportId;
    }

    public function withTransportId(TransportId $transportId): GetShippingLabel
    {
        return new self($transportId);
    }
}
