<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\ProcessStatus\Query;

final class GetStatusByProcessIds extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    const MESSAGE_NAME = 'BolCom\RetailerApi\Model\ProcessStatus\Query\GetStatusByProcessIds';

    protected $messageName = self::MESSAGE_NAME;

    /**
     * @return string[]
     */
    public function ids(): array
    {
        return $this->payload['ids'];
    }

        /**
     * @param string[]|null $ids
     */
public static function with(string ...$ids): GetStatusByProcessIds
    {
        return new self([
            'ids' => $ids,
        ]);
    }

    protected function setPayload(array $payload)
    {
        if (! isset($payload['ids']) || ! \is_array($payload['ids'])) {
            throw new \InvalidArgumentException("Key 'ids' is missing in payload or is not an array");
        }

        foreach ($payload['ids'] as $__value) {
            if (! \is_string($__value)) {
               throw new \InvalidArgumentException("'ids' is not an array of string");
            }
        }

        $this->payload = $payload;
    }
}
