<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Offer\Command;

final class UpdateOfferStock extends \Prooph\Common\Messaging\Command
{
    use \Prooph\Common\Messaging\PayloadTrait;

    const MESSAGE_NAME = 'BolCom\RetailerApi\Model\Offer\Command\UpdateOfferStock';

    protected $messageName = self::MESSAGE_NAME;

    public function offerId(): \BolCom\RetailerApi\Model\Offer\OfferId
    {
        return \BolCom\RetailerApi\Model\Offer\OfferId::fromString($this->payload['offerId']);
    }

    public function stock(): \BolCom\RetailerApi\Model\Offer\Stock
    {
        return \BolCom\RetailerApi\Model\Offer\Stock::fromArray($this->payload['stock']);
    }

    public static function with(\BolCom\RetailerApi\Model\Offer\OfferId $offerId, \BolCom\RetailerApi\Model\Offer\Stock $stock): UpdateOfferStock
    {
        return new self([
            'offerId' => $offerId->toString(),
            'stock' => $stock->toArray(),
        ]);
    }

    protected function setPayload(array $payload)
    {
        if (! isset($payload['offerId']) || ! \is_string($payload['offerId'])) {
            throw new \InvalidArgumentException("Key 'offerId' is missing in payload or is not a string");
        }

        if (! isset($payload['stock']) || ! \is_array($payload['stock'])) {
            throw new \InvalidArgumentException("Key 'stock' is missing in payload or is not an array");
        }

        $this->payload = $payload;
    }
}
