<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Inbound;

final class GetShipmentListResponse extends ShipmentList
{
    private $totalCount;
    private $totalPageCount;

    public function __construct(int $totalCount, int $totalPageCount)
    {
        $this->totalCount = $totalCount;
        $this->totalPageCount = $totalPageCount;
    }

    public function totalCount(): int
    {
        return $this->totalCount;
    }

    public function totalPageCount(): int
    {
        return $this->totalPageCount;
    }

    public function withTotalCount(int $totalCount): ShipmentList
    {
        return new self($totalCount, $this->totalPageCount);
    }

    public function withTotalPageCount(int $totalPageCount): ShipmentList
    {
        return new self($this->totalCount, $totalPageCount);
    }
}
