<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Inbound;

final class InboundList
{
    private $totalCount;
    private $totalPageCount;
    private $inbounds;

    public function __construct(int $totalCount, int $totalPageCount, array $inbounds)
    {
        $this->totalCount = $totalCount;
        $this->totalPageCount = $totalPageCount;
        foreach ($inbounds as $__value) {
            if (! $__value instanceof \BolCom\RetailerApi\Model\Inbound\Inbound) {
                throw new \InvalidArgumentException('inbounds expected an array of BolCom\RetailerApi\Model\Inbound\Inbound');
            }
            $this->inbounds[] = $__value;
        }
    }

    public function totalCount(): int
    {
        return $this->totalCount;
    }

    public function totalPageCount(): int
    {
        return $this->totalPageCount;
    }

    public function inbounds(): array
    {
        return $this->inbounds;
    }

    public function withTotalCount(int $totalCount): InboundList
    {
        return new self($totalCount, $this->totalPageCount, $this->inbounds);
    }

    public function withTotalPageCount(int $totalPageCount): InboundList
    {
        return new self($this->totalCount, $totalPageCount, $this->inbounds);
    }

    public function withInbounds(array $inbounds): InboundList
    {
        return new self($this->totalCount, $this->totalPageCount, $inbounds);
    }

    public static function fromArray(array $data): InboundList
    {
        if (! isset($data['totalCount']) || ! \is_int($data['totalCount'])) {
            throw new \InvalidArgumentException("Key 'totalCount' is missing in data array or is not a int");
        }

        $totalCount = $data['totalCount'];

        if (! isset($data['totalPageCount']) || ! \is_int($data['totalPageCount'])) {
            throw new \InvalidArgumentException("Key 'totalPageCount' is missing in data array or is not a int");
        }

        $totalPageCount = $data['totalPageCount'];

        if (! isset($data['inbounds']) || ! \is_array($data['inbounds'])) {
            throw new \InvalidArgumentException("Key 'inbounds' is missing in data array or is not an array");
        }

        $inbounds = [];

        foreach ($data['inbounds'] as $__value) {
            if (! \is_array($data['inbounds'])) {
                throw new \InvalidArgumentException("Key 'inbounds' in data array or is not an array of arrays");
            }

            $inbounds[] = Inbound::fromArray($__value);
        }

        return new self(
            $totalCount,
            $totalPageCount,
            $inbounds
        );
    }
}
