<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Inbound;

final class InventoryQuantityInput
{
    private $value;

    public function __construct(string $value)
    {
        if (!\Assert\Assertion::betweenLength($value, 0, 500)) {
            throw new \InvalidArgumentException('');
        }

        $this->value = $value;
    }

    public function value(): string
    {
        return $this->value;
    }

    public static function fromString(string $inventoryQuantityInput): InventoryQuantityInput
    {
        return new self($inventoryQuantityInput);
    }

    public function toString(): string
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}
