<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Inbound;

final class StateTransition
{
    private $state;
    private $stateDate;

    public function __construct(State $state, \BolCom\RetailerApi\Model\DateTime $stateDate)
    {
        $this->state = $state;
        $this->stateDate = $stateDate;
    }

    public function state(): State
    {
        return $this->state;
    }

    public function stateDate(): \BolCom\RetailerApi\Model\DateTime
    {
        return $this->stateDate;
    }

    public function withState(State $state): StateTransition
    {
        return new self($state, $this->stateDate);
    }

    public function withStateDate(\BolCom\RetailerApi\Model\DateTime $stateDate): StateTransition
    {
        return new self($this->state, $stateDate);
    }
}
