<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Inbound;

final class StateTransition
{
    private $state;
    private $stateDate;

    public function __construct(State $state, \BolCom\RetailerApi\Model\DateTime $stateDate)
    {
        $this->state = $state;
        $this->stateDate = $stateDate;
    }

    public function state(): State
    {
        return $this->state;
    }

    public function stateDate(): \BolCom\RetailerApi\Model\DateTime
    {
        return $this->stateDate;
    }

    public function withState(State $state): StateTransition
    {
        return new self($state, $this->stateDate);
    }

    public function withStateDate(\BolCom\RetailerApi\Model\DateTime $stateDate): StateTransition
    {
        return new self($this->state, $stateDate);
    }

    public static function fromArray(array $data): StateTransition
    {
        if (! isset($data['state']) || ! \is_string($data['state'])) {
            throw new \InvalidArgumentException("Key 'state' is missing in data array or is not a string");
        }

        $state = State::fromValue($data['state']);

        if (! isset($data['stateDate']) || ! \is_string($data['stateDate'])) {
            throw new \InvalidArgumentException("Key 'stateDate' is missing in data array or is not a string");
        }

        $stateDate = \BolCom\RetailerApi\Model\DateTime::fromString($data['stateDate']);

        return new self($state, $stateDate);
    }
}
