<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Inbound;

final class Timeslot
{
    private $start;
    private $end;

    public function __construct(\BolCom\RetailerApi\Model\DateTime $start, \BolCom\RetailerApi\Model\DateTime $end)
    {
        $this->start = $start;
        $this->end = $end;
    }

    public function start(): \BolCom\RetailerApi\Model\DateTime
    {
        return $this->start;
    }

    public function end(): \BolCom\RetailerApi\Model\DateTime
    {
        return $this->end;
    }

    public function withStart(\BolCom\RetailerApi\Model\DateTime $start): Timeslot
    {
        return new self($start, $this->end);
    }

    public function withEnd(\BolCom\RetailerApi\Model\DateTime $end): Timeslot
    {
        return new self($this->start, $end);
    }

    public static function fromArray(array $data): Timeslot
    {
        if (! isset($data['start']) || ! \is_string($data['start'])) {
            throw new \InvalidArgumentException("Key 'start' is missing in data array or is not a string");
        }

        $start = \BolCom\RetailerApi\Model\DateTime::fromString($data['start']);

        if (! isset($data['end']) || ! \is_string($data['end'])) {
            throw new \InvalidArgumentException("Key 'end' is missing in data array or is not a string");
        }

        $end = \BolCom\RetailerApi\Model\DateTime::fromString($data['end']);

        return new self($start, $end);
    }
}
