<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Inbound;

final class TimeslotList
{
    private $timeslot;

    public function __construct(Timeslot ...$timeslot)
    {
        $this->timeslot = $timeslot;
    }

    public function timeslot(): array
    {
        return $this->timeslot;
    }

    public function withTimeslot(array $timeslot): TimeslotList
    {
        return new self(...$timeslot);
    }
}
