<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Shipment;

final class ShipmentOrder
{
    private $orderId;
    private $orderPlacedDateTime;

    public function __construct(\BolCom\RetailerApi\Model\Order\OrderId $orderId = null, \BolCom\RetailerApi\Model\DateTime $orderPlacedDateTime = null)
    {
        $this->orderId = $orderId;
        $this->orderPlacedDateTime = $orderPlacedDateTime;
    }

    public function orderId()
    {
        return $this->orderId;
    }

    public function orderPlacedDateTime()
    {
        return $this->orderPlacedDateTime;
    }

    public function withOrderId(\BolCom\RetailerApi\Model\Order\OrderId $orderId = null): ShipmentOrder
    {
        return new self($orderId, $this->orderPlacedDateTime);
    }

    public function withOrderPlacedDateTime(\BolCom\RetailerApi\Model\DateTime $orderPlacedDateTime = null): ShipmentOrder
    {
        return new self($this->orderId, $orderPlacedDateTime);
    }

    public static function fromArray(array $data): ShipmentOrder
    {
        if (isset($data['orderId'])) {
            if (! \is_string($data['orderId'])) {
                throw new \InvalidArgumentException("Value for 'orderId' is not a string in data array");
            }

            $orderId = \BolCom\RetailerApi\Model\Order\OrderId::fromString($data['orderId']);
        } else {
            $orderId = null;
        }

        if (isset($data['orderPlacedDateTime'])) {
            if (! \is_string($data['orderPlacedDateTime'])) {
                throw new \InvalidArgumentException("Value for 'orderPlacedDateTime' is not a string in data array");
            }

            $orderPlacedDateTime = \BolCom\RetailerApi\Model\DateTime::fromString($data['orderPlacedDateTime']);
        } else {
            $orderPlacedDateTime = null;
        }

        return new self($orderId, $orderPlacedDateTime);
    }
}
