<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Shipment;

final class ShipmentList
{
    private $shipments;

    /**
     * @param \BolCom\RetailerApi\Model\Shipment\ShipmentListItem[]|null $shipments
     */
    public function __construct(ShipmentListItem ...$shipments)
    {
        $this->shipments = $shipments;
    }

    /**
     * @return \BolCom\RetailerApi\Model\Shipment\ShipmentListItem[]
     */
    public function shipments(): array
    {
        return $this->shipments;
    }

    /**
     * @param \BolCom\RetailerApi\Model\Shipment\ShipmentListItem[]|null $shipments
     * @return \BolCom\RetailerApi\Model\Shipment\ShipmentList
     */
    public function withShipments(array $shipments): ShipmentList
    {
        return new self(...$shipments);
    }

    public static function fromArray(array $data): ShipmentList
    {
        if (! isset($data['shipments']) || ! \is_array($data['shipments'])) {
            throw new \InvalidArgumentException("Key 'shipments' is missing in data array or is not an array");
        }

        $shipments = [];

        foreach ($data['shipments'] as $__value) {
            if (! \is_array($data['shipments'])) {
                throw new \InvalidArgumentException("Key 'shipments' in data array or is not an array of arrays");
            }

            $shipments[] = ShipmentListItem::fromArray($__value);
        }

        return new self(...$shipments);
    }
}
