<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Shipment;

final class ShipmentItem
{
    private $shipmentOrderItem;

    public function __construct(ShipmentOrderItem $shipmentOrderItem)
    {
        $this->shipmentOrderItem = $shipmentOrderItem;
    }

    public function shipmentOrderItem(): ShipmentOrderItem
    {
        return $this->shipmentOrderItem;
    }

    public function withShipmentOrderItem(ShipmentOrderItem $shipmentOrderItem): ShipmentItem
    {
        return new self($shipmentOrderItem);
    }

    public static function fromArray(array $data): ShipmentItem
    {
        if (! isset($data['shipmentOrderItem']) || ! \is_array($data['shipmentOrderItem'])) {
            throw new \InvalidArgumentException("Key 'shipmentOrderItem' is missing in data array or is not an array");
        }

        $shipmentOrderItem = ShipmentOrderItem::fromArray($data['shipmentOrderItem']);

        return new self($shipmentOrderItem);
    }
}
