<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Shipment;

final class ShipmentOffer
{
    private $offerId;
    private $reference;

    public function __construct(\BolCom\RetailerApi\Model\Offer\OfferId $offerId, \BolCom\RetailerApi\Model\Offer\Reference $reference)
    {
        $this->offerId = $offerId;
        $this->reference = $reference;
    }

    public function offerId(): \BolCom\RetailerApi\Model\Offer\OfferId
    {
        return $this->offerId;
    }

    public function reference(): \BolCom\RetailerApi\Model\Offer\Reference
    {
        return $this->reference;
    }

    public function withOfferId(\BolCom\RetailerApi\Model\Offer\OfferId $offerId): ShipmentOffer
    {
        return new self($offerId, $this->reference);
    }

    public function withReference(\BolCom\RetailerApi\Model\Offer\Reference $reference): ShipmentOffer
    {
        return new self($this->offerId, $reference);
    }

    public static function fromArray(array $data): ShipmentOffer
    {
        if (! isset($data['offerId']) || ! \is_string($data['offerId'])) {
            throw new \InvalidArgumentException("Key 'offerId' is missing in data array or is not a string");
        }

        $offerId = \BolCom\RetailerApi\Model\Offer\OfferId::fromString($data['offerId']);

        if (! isset($data['reference']) || ! \is_string($data['reference'])) {
            throw new \InvalidArgumentException("Key 'reference' is missing in data array or is not a string");
        }

        $reference = \BolCom\RetailerApi\Model\Offer\Reference::fromString($data['reference']);

        return new self($offerId, $reference);
    }
}
