<?php

// phpcs:ignoreFile
// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Invoice\Query;

final class GetInvoice extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    const MESSAGE_NAME = 'BolCom\RetailerApi\Model\Invoice\Query\GetInvoice';

    protected $messageName = self::MESSAGE_NAME;

    public function invoiceId(): \BolCom\RetailerApi\Model\Invoice\InvoiceId
    {
        return \BolCom\RetailerApi\Model\Invoice\InvoiceId::fromScalar($this->payload['invoiceId']);
    }

    public static function with(\BolCom\RetailerApi\Model\Invoice\InvoiceId $invoiceId): GetInvoice
    {
        return new self([
            'invoiceId' => $invoiceId->toScalar(),
        ]);
    }

    protected function setPayload(array $payload)
    {
        if (! isset($payload['invoiceId']) || ! \is_int($payload['invoiceId'])) {
            throw new \InvalidArgumentException("Key 'invoiceId' is missing in payload or is not a int");
        }

        $this->payload = $payload;
    }
}
