<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Invoice\Query;

final class GetInvoiceList
{
    private $period;

    public function __construct(\BolCom\RetailerApi\Model\Invoice\Period $period)
    {
        $this->period = $period;
    }

    public function period(): \BolCom\RetailerApi\Model\Invoice\Period
    {
        return $this->period;
    }

    public function withPeriod(\BolCom\RetailerApi\Model\Invoice\Period $period): GetInvoiceList
    {
        return new self($period);
    }
}
