<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Invoice\Query;

final class GetInvoice
{
    private $invoiceId;

    public function __construct(\BolCom\RetailerApi\Model\Invoice\InvoiceId $invoiceId)
    {
        $this->invoiceId = $invoiceId;
    }

    public function invoiceId(): \BolCom\RetailerApi\Model\Invoice\InvoiceId
    {
        return $this->invoiceId;
    }

    public function withInvoiceId(\BolCom\RetailerApi\Model\Invoice\InvoiceId $invoiceId): GetInvoice
    {
        return new self($invoiceId);
    }
}
