<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Invoice\Query;

final class GetInvoiceSpecification
{
    private $invoiceId;
    private $page;

    public function __construct(\BolCom\RetailerApi\Model\Invoice\InvoiceId $invoiceId, ?int $page)
    {
        $this->invoiceId = $invoiceId;
        $this->page = $page;
    }

    public function invoiceId(): \BolCom\RetailerApi\Model\Invoice\InvoiceId
    {
        return $this->invoiceId;
    }

    public function page(): ?int
    {
        return $this->page;
    }

    public function withInvoiceId(\BolCom\RetailerApi\Model\Invoice\InvoiceId $invoiceId): GetInvoiceSpecification
    {
        return new self($invoiceId, $this->page);
    }

    public function withPage(?int $page): GetInvoiceSpecification
    {
        return new self($this->invoiceId, $page);
    }
}
