<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace BolCom\RetailerApi\Model\Transport;

final class TransportInstruction
{
    private $transporterCode;
    private $trackAndTrace;

    public function __construct(TransporterCode $transporterCode, TrackAndTrace $trackAndTrace)
    {
        $this->transporterCode = $transporterCode;
        $this->trackAndTrace = $trackAndTrace;
    }

    public function transporterCode(): TransporterCode
    {
        return $this->transporterCode;
    }

    public function trackAndTrace(): TrackAndTrace
    {
        return $this->trackAndTrace;
    }

    public function withTransporterCode(TransporterCode $transporterCode): TransportInstruction
    {
        return new self($transporterCode, $this->trackAndTrace);
    }

    public function withTrackAndTrace(TrackAndTrace $trackAndTrace): TransportInstruction
    {
        return new self($this->transporterCode, $trackAndTrace);
    }
}
